jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWRvbHBoYWdvLXJlYWx3b3JsZC1wcm9qZWN0LWJhY2tlbmQtc3ByaW5nLWJvb3Qtc2VjdXJpdHktZG9scGhhZ28K # spring-boot-security-jwt-dolphago-realworld-project-backend-spring-boot-security-dolphago
