spring:
  application:
    name: realworld
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:real-world;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

jwt:
  secret : c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWNoYW5jZS1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  token-validity-in-seconds: 1800
# $ echo 'spring-boot-security-jwt-tutorial-chance-spring-boot-security-jwt-tutorial' | base64
