spring:
  application:
    name: realworld
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:real-world;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true

server:
  port: 8080

jwt:
  secret: 29effa2dab94e8f33f431d7694e2d47d4eb3999e653fdb9c8c811c0fbab245d1d5c8fba1d405758836b4193a44ecb9308543238bbadfa575cd5e3ee798d2d42e
  access-time: 1800000
