spring:
  application:
    name: realworld
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:real-world;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging.level:
  org.hibernate.SQL: debug
server:
  port: 8080
  servlet:
    context-path: /api
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
# $ echo 'spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial' | base64
