### join
POST localhost:8080/api/users
Content-Type: application/json

{
  "user": {
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

### join
POST localhost:8080/api/users
Content-Type: application/json

{
  "user": {
    "username": "JacobFriend",
    "email": "jakefriend@jake.jake",
    "password": "jakejake"
  }
}

### login
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

> {%
 client.global.set("Authorization", response.body.user.token);
 client.log("created Authorization: " + client.global.get("Authorization"));
%}

### login friend
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "jakefriend@jake.jake",
    "password": "jakejake"
  }
}

> {%
 client.global.set("Authorization", response.body.user.token);
 client.log("created Authorization: " + client.global.get("Authorization"));
%}

### update
PUT localhost:8080/api/user
Authorization: Token {{Authorization}}
Content-Type: application/json

{
  "user": {
    "email": "jake@jake2.jake",
    "bio": "I like to skateboard",
    "image": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}

### follow
POST localhost:8080/api/profiles/JacobFriend/follow
Authorization: Token {{Authorization}}

### get profile
GET localhost:8080/api/profiles/JacobFriend
Authorization: Token {{Authorization}}
