### JOIN
POST localhost:8080/api/users
Content-Type: application/json

{
  "user" :{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

### LOGIN
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "user" :{
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

> {%
 client.global.set("Authorization", response.body.user.token);
 client.log("생성된 Authorization : " + client.global.get("Authorization"));
%}

### UPDATE
PUT localhost:8080/api/members
Content-Type: application/json
Authorization: {{Authorization}}

{
  "user":{
    "userEmail": "jake@jake2.jake",
    "userBio": "I like to skateboard",
    "userImage": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}

### FAIL_UPDATE
PUT localhost:8080/api/members
Content-Type: application/json
Authorization: testestestsetestestestest

{
  "user":{
    "userEmail": "jake@jake2.jake",
    "userBio": "I like to skateboard",
    "userImage": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}

### FAIL_LOGIN
POST localhost:8080/api/members/login
Content-Type: application/json

{
  "user":{
    "userEmail": "jake2@jake.jake",
    "userPassword": "jakejake"
  }
}